### PR TITLE
Add current turn to game

### PR DESCRIPTION
**Pull request by taparkins**
While digging into creating API endpoints for issuing / viewing commands, I realized we will either need a historical reference to each unit through the game, or regenerating each game state from the beginning to know where the units were for historical records. And how that's handled will impact how I want to implement the command data model, so... instead let's just add a current turn to the game. :)

Tagging @taylor1791 and @ashley-dunn for review

### CODE REVIEW

**Comment by taylor1791** [comment]
+1 :blonde_woman: <- Not Ashley. Yet...

**Comment by aedunn6** [comment]
@taylor1791 I don't feel like I have enough familiarity with the project to give it a review on my own. 

@aparkins can we sit down together and go through this together?

**Comment by taparkins** [comment]
Adjusted per discussion with @taylor1791 this afternoon. Turns are saved as integers, but sent through API as structured { year, season, phase }. Put in some constants to cover the data, and updated tests. I also adjusted the game endpoint to only return players, units, and territories if the game has already begun (turn > 0).

Oh, and `BadRequestError` added for good measure. Didn't need it now, but we will soon enough.

**Comment by aedunn6** [comment]
+1 👨 ♀

**Pull request merged**
